---
title: \textbf{Uso de Anticonceptivos Hormonales y su relación con la Obesidad}
subtitle:
author: "ANIBAL RAUL ACUÑA MARTINEZ"
date: 

output:
  pdf_document:
    includes:
      in_header:
       # - Config.txt     # Configuracion de pie, encabezado y usepackge
  
---


```{r setup, include=FALSE}
# Configuración general
knitr::opts_chunk$set(
  comment = "",
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  eval = TRUE,
  echo = TRUE,
  include = TRUE
)

```






\begin{center} \textbf{MARCO TEÓRICO} \end{center}


Estudio Prospectivo: (CAUSALIDA)

Estudio Transversal: (ASOCIACIONES)

Estudio de Casos y Controles: (ASOCIACIONES)


**Modelo de Cox:** \textcolor{purple}{Ocurrencia de un evento de interés (como el desarrollo de obesidad) en función de una o más variables predictoras.}

**Regresion Logística:**  \textcolor{blue}{La regresión logística no proporciona información sobre el momento exacto en que ocurre el evento, solo la probabilidad de que ocurra en el período de estudio.}



Los anticonceptivos hormonales son métodos utilizados para prevenir el embarazo y regular el ciclo menstrual, y se presentan en varias formas, como píldoras, parches, anillos, implantes y dispositivos intrauterinos (DIU) hormonales. Estos métodos actúan alterando el equilibrio hormonal del cuerpo para prevenir la ovulación, modificar el revestimiento del útero y espesar el moco cervical.

La obesidad, definida como un exceso de grasa corporal con un índice de masa corporal (IMC) de 30 o superior, es una condición multifactorial con implicaciones significativas para la salud. La relación entre el uso de anticonceptivos hormonales y la obesidad ha sido objeto de investigación y debate.  Por otra parte los anticonceptivos hormonales pueden contener combinaciones de estrógenos y progestágenos (anticonceptivos combinados) o solo progestágenos (anticonceptivos progestágenos).  

Los Anticonceptivos progestágenos suelen contener estrógenos y progestágenos que actuan previniendo la ovulacvión; ademas alteran el moco cervical para retener el paso de espermatozoides y modifican el endometrio para reducir las probabilidades de implantación. Para el caso de los anticonceptivos Progestágenos solo poseen progesatágenos que actuan espesando el moco cervical y transforman el endometrio. 

Estudios han mostrado resultados mixtos, pero se han identificado varios mecanismos que podrían influir en la relación entre el uso de anticonceptivos hormonales y obesidad. A su vez el impacto de los anticonceptivos hormonales en el peso corporal y la composición corporal puede variar según el tipo de anticonceptivo y las características individuales de la usuaria. Algunos factores involucrados subbrayan que la retención de liquidos, los canbio de apetito o alteraciones en el metabolismo y los cambios en la composición corporal podrian estar sujetos al uso de estrógenos en los anticonceptivos.


#### 4. Evidencia Empírica

La investigación sobre la relación entre anticonceptivos hormonales y obesidad ha producido resultados variados:

- **Estudios Observacionales:** Algunos estudios observacionales han encontrado que el uso de anticonceptivos hormonales se asocia con un ligero aumento de peso, pero estos efectos pueden ser pequeños y varían entre individuos.

- **Estudios Clínicos Controlados:** Los ensayos clínicos controlados han mostrado que, en general, el aumento de peso asociado con el uso de anticonceptivos hormonales es mínimo y a menudo se limita a la retención de líquidos. Sin embargo, el impacto puede ser más significativo en ciertos subgrupos de mujeres.

- **Estudios sobre Diferentes Tipos de Anticonceptivos:** La relación entre anticonceptivos hormonales y obesidad puede diferir según el tipo de anticonceptivo. Por ejemplo, los anticonceptivos que contienen solo progestágenos pueden estar más asociados con cambios en el peso corporal en comparación con los anticonceptivos combinados.




\newpage

- Anticonceptivos hormonales y su relación con la obesidad en usuarias continuadoras del centro de salud Mala – Cañete, 2021. 	<http://repositorio.autonomadeica.edu.pe/handle/autonomadeica/1907>

- Nappi RE, Pellegrinelli A, Campolo F, Lanzo G, Santamaria V, Suragna A, et al. Effects of combined hormonal contraception on health and wellbeing: women’s knowledge in northern Italy. Eur J. <https://www.tandfonline.com/doi/epdf/10.1080/09513590.2023.2189971?needAccess=true>

- Contracept Reprod Health Care. 2015;20(1):36–46.
Venkat P, Masch R, Ng E, Cremer M, Richman S, Arslan A. Knowledge and beliefs about contraception in urban Latina women. J Community Health, 2008;33(5):357–62.

- Gilliam ML, Warden M, Goldstein C, Tapia B. Concerns about contraceptive side effects among young Latinas: a focus-group approach. Contraception. 2004;70:288-305.

- Rosenburg MJ, Waugh MS, Meehan TE. Use and misuse of oral contraceptives: risk indicators for poor pill taking and discontinuation. Contraception. 1995;51(5):283-8.

- Sangi-Haghpeykar H, Poindexter AN, Bateman L, Ditmore JR. Experiences of injectable contraceptive users in an urban setting. Obstet Gynecol. 1996;88(2):227-33.

- Paul C, Skegg DC, Williams S. Depot medroxyprogesterone acetate. Patterns of use and reasons for discontinuation. Contraception. 1997;56(4):209-14.

- Leeners B, Geary N, Tobler PN, Asarian L. Ovarian hormones and obesity. Hum Reprod Update. 2017;23(3):300-21.

- Karvonen-Gutierrez C, Kim C. Association of mid-life changes in body size, body composition and obesity status with the menopausal transition. Healthcare. 2016;4(3).

- Gallo MF, Lopez LM, Grimes DA, Carayon F, Schulz KF, Helmerhost FM. Combination contraceptives: effects on weight. Cochrane Database Syst Rev. 2014;(1):CD003987.

- Lopez LM, Ramesh S, Chen M, Edelman A, Otterness C, Trussel J, et al. Progestin-only contraceptives: effects on weight. Cochrane Database Syst Rev. 2016;(8):CD008815.





