

CREATE TABLE saber11_2019 (
    ESTU_TIPODOCUMENTO VARCHAR(20),
    ESTU_NACIONALIDAD VARCHAR(50),
    ESTU_GENERO VARCHAR(10),
    ESTU_FECHANACIMIENTO DATE,
    PERIODO INT,
    ESTU_CONSECUTIVO VARCHAR(20),
    ESTU_ESTUDIANTE VARCHAR(20),
    ESTU_TIENEETNIA VARCHAR(10),
    ESTU_PAIS_RESIDE VARCHAR(50),
    ESTU_ETNIA VARCHAR(50),
    ESTU_DEPTO_RESIDE VARCHAR(50),
    ESTU_COD_RESIDE_DEPTO INT,
    ESTU_MCPIO_RESIDE VARCHAR(50),
    ESTU_COD_RESIDE_MCPIO INT,
    FAMI_ESTRATOVIVIENDA VARCHAR(20),
    FAMI_PERSONASHOGAR VARCHAR(20),
    FAMI_CUARTOSHOGAR VARCHAR(20),
    FAMI_EDUCACIONPADRE VARCHAR(50),
    FAMI_EDUCACIONMADRE VARCHAR(50),
    FAMI_TRABAJOLABORPADRE VARCHAR(50),
    FAMI_TRABAJOLABORMADRE VARCHAR(50),
    FAMI_TIENEINTERNET VARCHAR(10),
    FAMI_TIENESERVICIOTV VARCHAR(10),
    FAMI_TIENECOMPUTADOR VARCHAR(10),
    FAMI_TIENELAVADORA VARCHAR(10),
    FAMI_TIENEHORNOMICROOGAS VARCHAR(10),
    FAMI_TIENEAUTOMOVIL VARCHAR(10),
    FAMI_TIENEMOTOCICLETA VARCHAR(10),
    FAMI_TIENECONSOLAVIDEOJUEGOS VARCHAR(10),
    FAMI_NUMLIBROS VARCHAR(20),
    FAMI_COMELECHEDERIVADOS VARCHAR(50),
    FAMI_COMECARNEPESCADOHUEVO VARCHAR(50),
    FAMI_COMECEREALFRUTOSLEGUMBRE VARCHAR(50),
    FAMI_SITUACIONECONOMICA VARCHAR(50),
    ESTU_DEDICACIONLECTURADIARIA VARCHAR(50),
    ESTU_DEDICACIONINTERNET VARCHAR(50),
    ESTU_HORASSEMANATRABAJA INT,
    ESTU_TIPOREMUNERACION VARCHAR(50),
    COLE_CODIGO_ICFES INT,
    COLE_COD_DANE_ESTABLECIMIENTO VARCHAR(50),
    COLE_NOMBRE_ESTABLECIMIENTO VARCHAR(100),
    COLE_GENERO VARCHAR(20),
    COLE_NATURALEZA VARCHAR(50),
    COLE_CALENDARIO VARCHAR(20),
    COLE_BILINGUE VARCHAR(10),
    COLE_CARACTER VARCHAR(50),
    COLE_COD_DANE_SEDE VARCHAR(50),
    COLE_NOMBRE_SEDE VARCHAR(100),
    COLE_SEDE_PRINCIPAL VARCHAR(10),
    COLE_AREA_UBICACION VARCHAR(20),
    COLE_JORNADA VARCHAR(20),
    COLE_COD_MCPIO_UBICACION INT,
    COLE_MCPIO_UBICACION VARCHAR(50),
    COLE_COD_DEPTO_UBICACION INT,
    COLE_DEPTO_UBICACION VARCHAR(50),
    ESTU_PRIVADO_LIBERTAD VARCHAR(10),
    ESTU_COD_MCPIO_PRESENTACION INT,
    ESTU_MCPIO_PRESENTACION VARCHAR(50),
    ESTU_DEPTO_PRESENTACION VARCHAR(50),
    ESTU_COD_DEPTO_PRESENTACION INT,
    PUNT_LECTURA_CRITICA FLOAT,
    PERCENTIL_LECTURA_CRITICA FLOAT,
    DESEMP_LECTURA_CRITICA VARCHAR(10),
    PUNT_MATEMATICAS FLOAT,
    PERCENTIL_MATEMATICAS FLOAT,
    DESEMP_MATEMATICAS VARCHAR(10),
    PUNT_C_NATURALES FLOAT,
    PERCENTIL_C_NATURALES FLOAT,
    DESEMP_C_NATURALES VARCHAR(10),
    PUNT_SOCIALES_CIUDADANAS FLOAT,
    PERCENTIL_SOCIALES_CIUDADANAS FLOAT,
    DESEMP_SOCIALES_CIUDADANAS VARCHAR(10),
    PUNT_INGLES FLOAT,
    PERCENTIL_INGLES FLOAT,
    DESEMP_INGLES VARCHAR(10),
    PUNT_GLOBAL FLOAT,
    PERCENTIL_GLOBAL FLOAT,
    ESTU_INSE_INDIVIDUAL VARCHAR(50),
    ESTU_NSE_INDIVIDUAL INT,
    ESTU_NSE_ESTABLECIMIENTO INT,
    ESTU_ESTADOINVESTIGACION VARCHAR(50),
    ESTU_GENERACION_E VARCHAR(50)
);


### a. ¿Cuántos estudiantes hay por género (ESTU_GENERO)?


SELECT ESTU_GENERO, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
GROUP BY ESTU_GENERO;


### b. ¿Por departamento, cuántos del género femenino y cuántos del género masculino?


SELECT ESTU_DEPTO_RESIDE, ESTU_GENERO, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
GROUP BY ESTU_DEPTO_RESIDE, ESTU_GENERO;


### c. Para el departamento del Cesar, diga la distribución por género para cada uno de los municipios.


SELECT ESTU_MCPIO_RESIDE, ESTU_GENERO, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
WHERE ESTU_DEPTO_RESIDE = 'Cesar'
GROUP BY ESTU_MCPIO_RESIDE, ESTU_GENERO;


### d. Para el departamento del Cesar, diga la distribución para el desempeño en Inglés (DESEMP_INGLES) por municipios.


SELECT ESTU_MCPIO_RESIDE, DESEMP_INGLES, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
WHERE ESTU_DEPTO_RESIDE = 'Cesar'
GROUP BY ESTU_MCPIO_RESIDE, DESEMP_INGLES;


### e. Diga cuál es el promedio del puntaje global (PUNT_GLOBAL) para cada uno de los municipios del departamento del Cesar.


SELECT ESTU_MCPIO_RESIDE, AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL
FROM saber11_2019
WHERE ESTU_DEPTO_RESIDE = 'Cesar'
GROUP BY ESTU_MCPIO_RESIDE;


### f. Conozca el promedio del puntaje global nacional y compárelo con los obtenidos en el departamento del Cesar.

#### Promedio del puntaje global nacional:


SELECT AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL_NACIONAL
FROM saber11_2019;


#### Promedio del puntaje global en el departamento del Cesar:


SELECT AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL_CESAR
FROM saber11_2019
WHERE ESTU_DEPTO_RESIDE = 'Cesar';


### g. Para el departamento del Cesar, diga cuál es el promedio de: puntaje de lectura crítica (PUNT_LECTURA_CRITICA), puntaje de matemáticas (PUNT_MATEMATICAS), puntaje de ciencias naturales (PUNT_C_NATURALES), puntaje de competencia ciudadana (PUNT_SOCIALES_CIUDADANAS).

SELECT 
    AVG(PUNT_LECTURA_CRITICA) AS PROMEDIO_PUNT_LECTURA_CRITICA,
    AVG(PUNT_MATEMATICAS) AS PROMEDIO_PUNT_MATEMATICAS,
    AVG(PUNT_C_NATURALES) AS PROMEDIO_PUNT_C_NATURALES,
    AVG(PUNT_SOCIALES_CIUDADANAS) AS PROMEDIO_PUNT_SOCIALES_CIUDADANAS
FROM saber11_2019
WHERE ESTU_DEPTO_RESIDE = 'Cesar';











