---
title: \textbf{Conceptos N1 Bases de Datos}
subtitle: Bases de Datos
author: "Jose Angel Urquijo Parra"
date: \today

output:
  pdf_document:
    includes:
      in_header:
        - Config.txt     # Configuracion de pie, encabezado y usepackge
  
---


```{r setup, include=FALSE}
# Configuración general
knitr::opts_chunk$set(
  comment = "",
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  eval = TRUE,
  echo = TRUE,
  include = TRUE
)

```


```{r, include=FALSE}
library(RPostgres)
library(DBI)


# Crear la conexión utilizando RPostgres
conexion <- dbConnect(RPostgres::Postgres(), dbname = "Saber",
                      host = "localhost",
                      port = 5432,
                      user = "postgres",
                      password = "...")


knitr::opts_chunk$set(connection = conexion)

```


```{sql connection=conexion}
/*
CREATE TABLE saber11_2019 (
    ESTU_TIPODOCUMENTO CHARACTER VARYING(255),
    ESTU_NACIONALIDAD CHARACTER VARYING(255),
    ESTU_GENERO CHARACTER VARYING(255),
    ESTU_FECHANACIMIENTO DATE,
    PERIODO CHARACTER VARYING(255),
    ESTU_CONSECUTIVO CHARACTER VARYING(255),
    ESTU_ESTUDIANTE CHARACTER VARYING(255),
    ESTU_TIENEETNIA CHARACTER VARYING(255),
    ESTU_PAIS_RESIDE CHARACTER VARYING(255),
    ESTU_ETNIA CHARACTER VARYING(255),
    ESTU_DEPTO_RESIDE CHARACTER VARYING(255),
    ESTU_COD_RESIDE_DEPTO CHARACTER VARYING(255),
    ESTU_MCPIO_RESIDE CHARACTER VARYING(255),
    ESTU_COD_RESIDE_MCPIO CHARACTER VARYING(255),
    FAMI_ESTRATOVIVIENDA CHARACTER VARYING(255),
    FAMI_PERSONASHOGAR CHARACTER VARYING(255),
    FAMI_CUARTOSHOGAR CHARACTER VARYING(255),
    FAMI_EDUCACIONPADRE CHARACTER VARYING(255),
    FAMI_EDUCACIONMADRE CHARACTER VARYING(255),
    FAMI_TRABAJOLABORPADRE CHARACTER VARYING(255),
    FAMI_TRABAJOLABORMADRE CHARACTER VARYING(255),
    FAMI_TIENEINTERNET CHARACTER VARYING(255),
    FAMI_TIENESERVICIOTV CHARACTER VARYING(255),
    FAMI_TIENECOMPUTADOR CHARACTER VARYING(255),
    FAMI_TIENELAVADORA CHARACTER VARYING(255),
    FAMI_TIENEHORNOMICROOGAS CHARACTER VARYING(255),
    FAMI_TIENEAUTOMOVIL CHARACTER VARYING(255),
    FAMI_TIENEMOTOCICLETA CHARACTER VARYING(255),
    FAMI_TIENECONSOLAVIDEOJUEGOS CHARACTER VARYING(255),
    FAMI_NUMLIBROS CHARACTER VARYING(255),
    FAMI_COMELECHEDERIVADOS CHARACTER VARYING(255),
    FAMI_COMECARNEPESCADOHUEVO CHARACTER VARYING(255),
    FAMI_COMECEREALFRUTOSLEGUMBRE CHARACTER VARYING(255),
    FAMI_SITUACIONECONOMICA CHARACTER VARYING(255),
    ESTU_DEDICACIONLECTURADIARIA CHARACTER VARYING(255),
    ESTU_DEDICACIONINTERNET CHARACTER VARYING(255),
    ESTU_HORASSEMANATRABAJA CHARACTER VARYING(255),
    ESTU_TIPOREMUNERACION CHARACTER VARYING(255),
    COLE_CODIGO_ICFES CHARACTER VARYING(255),
    COLE_COD_DANE_ESTABLECIMIENTO CHARACTER VARYING(255),
    COLE_NOMBRE_ESTABLECIMIENTO CHARACTER VARYING(255),
    COLE_GENERO CHARACTER VARYING(255),
    COLE_NATURALEZA CHARACTER VARYING(255),
    COLE_CALENDARIO CHARACTER VARYING(255),
    COLE_BILINGUE CHARACTER VARYING(255),
    COLE_CARACTER CHARACTER VARYING(255),
    COLE_COD_DANE_SEDE CHARACTER VARYING(255),
    COLE_NOMBRE_SEDE CHARACTER VARYING(255),
    COLE_SEDE_PRINCIPAL CHARACTER VARYING(255),
    COLE_AREA_UBICACION CHARACTER VARYING(255),
    COLE_JORNADA CHARACTER VARYING(255),
    COLE_COD_MCPIO_UBICACION CHARACTER VARYING(255),
    COLE_MCPIO_UBICACION CHARACTER VARYING(255),
    COLE_COD_DEPTO_UBICACION CHARACTER VARYING(255),
    COLE_DEPTO_UBICACION CHARACTER VARYING(255),
    ESTU_PRIVADO_LIBERTAD CHARACTER VARYING(255),
    ESTU_COD_MCPIO_PRESENTACION CHARACTER VARYING(255),
    ESTU_MCPIO_PRESENTACION CHARACTER VARYING(255),
    ESTU_DEPTO_PRESENTACION CHARACTER VARYING(255),
    ESTU_COD_DEPTO_PRESENTACION CHARACTER VARYING(255),
    PUNT_LECTURA_CRITICA NUMERIC,
    PERCENTIL_LECTURA_CRITICA NUMERIC,
    DESEMP_LECTURA_CRITICA CHARACTER VARYING(255),
    PUNT_MATEMATICAS NUMERIC,
    PERCENTIL_MATEMATICAS NUMERIC,
    DESEMP_MATEMATICAS CHARACTER VARYING(255),
    PUNT_C_NATURALES NUMERIC,
    PERCENTIL_C_NATURALES NUMERIC,
    DESEMP_C_NATURALES CHARACTER VARYING(255),
    PUNT_SOCIALES_CIUDADANAS NUMERIC,
    PERCENTIL_SOCIALES_CIUDADANAS NUMERIC,
    DESEMP_SOCIALES_CIUDADANAS CHARACTER VARYING(255),
    PUNT_INGLES NUMERIC,
    PERCENTIL_INGLES NUMERIC,
    DESEMP_INGLES CHARACTER VARYING(255),
    PUNT_GLOBAL NUMERIC,
    PERCENTIL_GLOBAL NUMERIC,
    ESTU_INSE_INDIVIDUAL CHARACTER VARYING(255),
    ESTU_NSE_INDIVIDUAL CHARACTER VARYING(255),
    ESTU_NSE_ESTABLECIMIENTO CHARACTER VARYING(255),
    ESTU_ESTADOINVESTIGACION CHARACTER VARYING(255),
    ESTU_GENERACION_E CHARACTER VARYING(255)
);
*/


```



```{sql connection= conexion}
--- a. ¿Cuantos estudiantes hay por genero (ESTU_GENERO)?

SELECT estu_genero, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
WHERE estu_genero <> '0'
GROUP BY estu_genero;
```

```{sql connection= conexion}
--- b. ¿Por departamento, cuántos del género femenino y cuántos del género masculino?


SELECT estu_depto_reside, estu_genero, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
GROUP BY estu_depto_reside, estu_genero;
```

```{sql connection= conexion}
--- c. Distribución por género para cada uno de los municipios.


SELECT estu_mcpio_reside, estu_genero, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
WHERE estu_depto_reside = 'CESAR'
GROUP BY estu_mcpio_reside, estu_genero;

```

```{sql connection= conexion}
--- d. Distribución para el desempeño en Inglés (DESEMP_INGLES) por municipios.


SELECT estu_mcpio_reside, desemp_ingles, COUNT(*) AS NUM_ESTUDIANTES
FROM saber11_2019
WHERE estu_depto_reside = 'CESAR'
GROUP BY estu_mcpio_reside, desemp_ingles;
```

```{sql connection= conexion}
--- e. promedio del puntaje global para clos municipios del departamento del Cesar.


SELECT estu_mcpio_reside, AVG(punt_global) AS PROM_PUNT_GLOBAL
FROM saber11_2019
WHERE estu_depto_reside = 'CESAR'
GROUP BY estu_mcpio_reside;
```

```{sql connection= conexion}
--- Promedio del puntaje global nacional:


SELECT AVG(punt_global) AS PROM_PUNT_GLOBAL_NACIONAL
FROM saber11_2019;
```

```{sql connection= conexion}
--- Promedio del puntaje global nacional:


SELECT AVG(punt_global) AS PROM_PUNT_GLOBAL_NACIONAL
FROM saber11_2019;
```


```{sql connection= conexion}
--- Promedio del puntaje global en el departamento del Cesar:


SELECT AVG(punt_global) AS PROM_PUNT_GLOBAL_CESAR
FROM saber11_2019
WHERE estu_depto_reside = 'CESAR';

```

```{sql connection= conexion}
--- g. Promedio de:lectura crítica, matemáticas, ciencias naturales, competencia ciudadana

SELECT 
    AVG(punt_lectura_critica) AS PROM_LECTURA_CRITICA,
    AVG(punt_matematicas) AS PROM_MATEMATICAS,
    AVG(punt_c_naturales) AS PROM_NATURALES,
    AVG(punt_sociales_ciudadanas) AS PROM_CIUDADANAS
FROM saber11_2019
WHERE estu_depto_reside = 'CESAR';
```



