---
title: \textbf{Sistemas de Gestión de Bases de Datos}
subtitle: Asignatura Bases De Datos
author: "Jose Angel Urquijo Parra"
date: \today
  
output:
  pdf_document:
    toc: no               # Indice de paginas
    #number_sections: no  # Innecesario 
    highlight: arrow      # Theme de sintaxis
    includes:
      in_header:
        - Config.txt     # Configuracion de pie, encabezado y usepackge
      #before_body: before_body.tex (Preambulo)
      #after_body: after_body.tex (Preambulo)
        
  params:
    lang: es
    csl: "apa.csl"
    geometry: "margin=1in"
    fontsize: 11pt
    mainfont: "Times New Roman"
    
        
knitr:
  opts_chunk:
    comment: ""          # Comentarios de salida para el chunk
    highlight: TRUE      # Sintaxis de Salida para el chunk
    fig.align: "center"  # Alinea los chunk al centro
    message: FALSE  # Evita mensajes de errores
    warning: FALSE  # Evita advertencias
    tidy: FALSE     # controla si el código en un chunk debe ser limpiado o reformateado
    eval: TRUE      # controla si el código en un chunk debe ser ejecutado o no al generar
    fig.cap: ""     # Leyenda grafica
    echo: TRUE      # controla si el código del chunk debe ser mostrado en el documento
    include: TRUE   # Incluye el codigo y sus resultados 
    cache: FALSE    # Formatea la memoria
    dpi: 300        # Numero de pixeles en resolucion para graficos
    error: FALSE    # No interfiere la salida y genera errores
    collapse: TRUE  # Organiza y limpia el formato de salida
    
    # Credencial de Acceso: 
    # git config --global user.name "Mi Nombre"
    # git config --global user.email jurquijop@unal.edu.co
---

Los sistemas de gestión de bases de datos (DBMS) han experimentado una evolución significativa desde sus inicios en las décadas de 1960 y 1970. Los modelos jerárquico y de red dominaban el panorama, como el IMS de IBM. La verdadera revolución en el campo de las bases de datos llegó con la introducción del modelo relacional por Edgar F. Codd en 1970. Este modelo, junto con el desarrollo del lenguaje SQL, transformó la forma en que los datos se almacenaban, consultaban y manipulaban. Durante los años 1980 y 1990, los sistemas relacionales, como Oracle, IBM DB2 y Microsoft SQL Server, se establecieron como estándares industriales, facilitando la transición hacia sistemas OLTP (Online Transaction Processing) y OLAP (Online Analytical Processing). 

La diferenciación entre sistemas transaccionales y analíticos permitió una optimización más especializada de las bases de datos, fomentando el desarrollo de tecnologías como data warehouses y data marts. La llegada del siglo XXI, el auge del Big Data y la necesidad de manejar datos no estructurados dieron lugar a las bases de datos NoSQL. Estas bases de datos, que incluyen categorías documentales, de claves-valor, de columnas y de grafos, se destacaron por su escalabilidad horizontal y flexibilidad, permitiendo el manejo eficiente de grandes volúmenes de datos distribuidos. Ejemplos notables incluyen MongoDB, Cassandra y Neo4j. Paralelamente, la aparición de tecnologías de procesamiento masivo como Hadoop y su ecosistema, incluyendo HDFS y MapReduce, revolucionaron el almacenamiento y análisis de datos a gran escala.

El desarrollo de NewSQL, con soluciones como Google Spanner y CockroachDB, intentó combinar lo mejor de los mundos relacional y NoSQL, ofreciendo consistencia transaccional junto con escalabilidad. Además, las bases de datos en memoria, como SAP HANA y Redis, comenzaron a ganar popularidad debido a su capacidad para proporcionar acceso ultrarrápido a los datos al almacenarlos en la memoria principal. Recientemente, tecnologías emergentes como las bases de datos distribuidas y el blockchain están ganando terreno, ofreciendo nuevas formas de almacenar y gestionar datos con alta disponibilidad y seguridad inmutable.

A pesar de estos avances, los DBMS enfrentan desafíos continuos en términos de seguridad y privacidad, especialmente con regulaciones como GDPR. La escalabilidad y el rendimiento siguen siendo preocupaciones clave, junto con la necesidad de integrar y compatibilizar diversas tecnologías de bases de datos en un ecosistema cohesionado. Mirando hacia el futuro, se anticipa que las bases de datos autónomas, que se auto-gestionan y optimizan, como la Oracle Autonomous Database, jugarán un papel crucial en la industria. La computación en el borde y la integración con IoT también están configuradas para transformar el panorama, permitiendo el procesamiento de datos en tiempo real cerca de la fuente de generación.

En conclusión, los sistemas de gestión de bases de datos están en una encrucijada de innovación continua y adaptación. Desde sus humildes comienzos en modelos jerárquicos y de red, pasando por la revolución relacional y la explosión del Big Data, hasta las promesas de NoSQL, NewSQL y tecnologías emergentes, los DBMS siguen siendo una piedra angular en la infraestructura tecnológica moderna, adaptándose constantemente para satisfacer las demandas cada vez más complejas y dinámicas del mundo digital.


## \textcolor{blue}{ Referencias Mundiales}

1. **The Relational Model for Database Management** por Edgar F. Codd

   <https://dl.acm.org/doi/pdf/10.5555/77708>

2. **Database System Concepts** por Abraham Silberschatz, Henry F. Korth y S. Sudarshan

   <https://drive.google.com/file/d/13q8K7vhvQaavlgoO1eJpKQHKjaTBh8dP/view>

3. **Database Management Systems** por Raghu Ramakrishnan y Johannes Gehrke

   <https://archive.org/details/ramakrishnan-database-management-systems-3rd-edition>

4. **Designing Data-Intensive Applications** por Martin Kleppmann

   <https://archive.org/details/designing-data-intensive-applications-the-big-ideas-behind-reliable-scalable-and>

5. **Big Data: Principles and best practices of scalable real-time data systems** por Nathan Marz y James Warren

   <https://www.manning.com/books/big-data>

### \textcolor{blue}{Referencias Latinoamericanas}

1. **Bases de Datos: Conceptos y Aplicaciones** por Rafael Corchuelo

   <https://www.universilibros.com/libro/bases-de-datos-conceptos-y-aplicaciones>

2. **Sistemas de Gestión de Bases de Datos** por Francisco José García Peñalvo

   <https://thedataschools.com/que-es/sistema-de-gestion-de-bases-de-datos/>

3. **Artículos de la Conferencia Latinoamericana de Informática (CLEI)**

   <https://conferencia2024.clei.org/>

4. **Revista Computación y Sistemas**

   <https://cys.cic.ipn.mx/>

### \textcolor{blue}{Referencia Nacional (Colombia)}

1. **Introducción a las bases de datos relacionales** por William H. Enríquez Muñoz

   <https://editorial.ucatolica.edu.co/introduccion-a-las-bases-de-datos-relacionales-william-h-enriquez-munoz/p>





