---
title: \textbf{Visualización Espacial de datos}
subtitle: Estadística Espacial
author: "Jose Angel Urquijo Parra"
date: \today

output:
  pdf_document:
    toc: no               # Indice de paginas
    #number_sections: no  # Innecesario 
    highlight: arrow      # Theme de sintaxis
    includes:
      in_header:
        - Config.txt     # Configuracion de pie, encabezado y usepackge
      #before_body: before_body.tex (Preambulo)
      #after_body: after_body.tex (Preambulo)
        
  params:
    lang: es
    csl: "apa.csl"
    geometry: "margin=1in"
    fontsize: 11pt
    mainfont: "Times New Roman"

---


```{r setup, include=FALSE}
# Configuración general
knitr::opts_chunk$set(
  comment = "",
  highlight = TRUE,
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  eval = TRUE,
  fig.cap = "",
  echo = TRUE,
  include = TRUE,
  cache = FALSE,
  dpi = 300,
  error = FALSE,
  collapse = TRUE
)

```

## \textcolor{blue}{Construcción del Variograma}

```{r}
library(gstat)
library(sp)
data("meuse")

# Cálculo del variograma
variograma <- variogram(log(zinc) ~ 1, data = meuse, locations = ~x+y)
plot(variograma)

```

```{r}
# Ajuste de un modelo teórico al variograma
model_fit <- fit.variogram(variograma, vgm(psill = 1, "Sph", range = 1, nugget = 0))
plot(variograma, model_fit)

```

## \textcolor{blue}{ Kriging(técnica de Interpolación)}

```{r}

data("meuse")
data("meuse.grid")

# Convertir meuse a SpatialPointsDataFrame
coordinates(meuse) <- ~x + y

# Convertir meuse.grid a SpatialPixelsDataFrame
gridded(meuse.grid) <- ~x + y

# Definir el variograma
vgm_model <- vgm(psill = 1, model = "Sph", range = 1000, nugget = 0)

# Ajustar el variograma a los datos
model_fit <- fit.variogram(variogram(log(zinc) ~ 1, meuse), model = vgm_model)

kriging_result <- krige(log(zinc) ~ 1, meuse, meuse.grid, model = model_fit)

# Visualización de los resultados de Kriging
spplot(kriging_result["var1.pred"])


```

## \textcolor{blue}{Evaluación de la Autocorrelación Espacial}


```{r}

library(sf)
library(spdep)

data("meuse", package = "sp")

# Convertir meuse a un objeto sf
meuse_sf <- st_as_sf(meuse, coords = c("x", "y"), crs = 4326)

# lista de vecinos utilizando knearneigh para datos de puntos
nb <- knn2nb(knearneigh(st_coordinates(meuse_sf), k = 4))

# pesos de los vecinos utilizando nb2listw
lw <- nb2listw(nb)

# test de Moran
moran_test <- moran.test(meuse$zinc, lw);moran_test


plot(st_geometry(meuse_sf), main = "Mapa de Vecinos con Zonas de Zinc", pch = 16, col = 'blue')
plot(nb, st_coordinates(meuse_sf), add = TRUE, col = 'red')


```



