---
title: \textbf{Asociación entre el Uso de Anticonceptivos Hormonales y el Riesgo de Obesidad en Usuarias}
subtitle:
author: ""
date: 

output:
  pdf_document:
    includes:
      in_header:
       # - Config.txt     # Configuracion de pie, encabezado y usepackge
  
---


```{r setup, include=FALSE}
# Configuración general
knitr::opts_chunk$set(
  comment = "",
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  eval = TRUE,
  echo = TRUE,
  include = TRUE
)

```






\begin{center} \textbf{MARCO TEÓRICO} \end{center}


Los anticonceptivos hormonales, ampliamente utilizados para prevenir el embarazo y regular el ciclo menstrual, se presentan en diversas formas, como píldoras, parches, anillos, implantes y dispositivos intrauterinos (DIU) hormonales. Estos métodos actúan modificando el equilibrio hormonal del cuerpo para inhibir la ovulación, alterar el revestimiento del útero y espesar el moco cervical, lo que reduce la probabilidad de fertilización e implantación.

La obesidad, definida como un exceso de grasa corporal con un índice de masa corporal (IMC) igual o superior a 30, es una condición multifactorial que conlleva importantes riesgos para la salud. La relación entre el uso de anticonceptivos hormonales y la obesidad ha sido objeto de considerable investigación y debate. Los anticonceptivos hormonales se clasifican en dos categorías principales: combinados, que contienen estrógenos y progestágenos, y aquellos que solo contienen progestágenos. Los anticonceptivos combinados previenen la ovulación, alteran el moco cervical para dificultar el paso de los espermatozoides, y modifican el endometrio para reducir las posibilidades de implantación. Por otro lado, los anticonceptivos que contienen solo progestágenos actúan espesando el moco cervical y transformando el endometrio, sin inhibir necesariamente la ovulación.

La literatura científica ha reportado resultados mixtos en cuanto a la relación entre el uso de anticonceptivos hormonales y la obesidad. Varios mecanismos han sido propuestos para explicar esta relación, incluyendo la retención de líquidos, cambios en el apetito, alteraciones en el metabolismo y variaciones en la composición corporal, especialmente en usuarios de anticonceptivos que contienen estrógenos.

En cuanto a la relación entre anticonceptivos hormonales, obesidad y el riesgo de desarrollar diabetes, los estudios han mostrado resultados diversos. Aunque algunos sugieren que los anticonceptivos hormonales pueden estar asociados con un leve aumento de peso, particularmente en los primeros meses de uso, la evidencia no es concluyente. La obesidad, un conocido factor de riesgo para la diabetes tipo 2, podría aumentar la probabilidad de desarrollar esta enfermedad en mujeres que utilizan anticonceptivos hormonales, especialmente en aquellas con predisposición genética o prediabetes. No obstante, el riesgo varía según el tipo de anticonceptivo, con algunos estudios indicando que los anticonceptivos solo con progestina podrían tener un mayor impacto en los niveles de glucosa en sangre.

**1. Estudios Observacionales:**
Los estudios observacionales han reportado que el uso de anticonceptivos hormonales puede estar asociado con un leve aumento de peso, aunque estos efectos suelen ser pequeños y varían entre individuos. Estos estudios no establecen una relación causal definitiva, pero sugieren que factores como la retención de líquidos y los cambios en el apetito pueden contribuir al aumento de peso observado en algunas usuarias. Sin embargo, la variabilidad en los resultados y la dificultad para controlar todos los factores externos hace que los hallazgos sean heterogéneos y no conclusivos en cuanto a un impacto significativo y generalizado del uso de anticonceptivos en el peso.

**2. Estudios Clínicos Controlados:**
Los ensayos clínicos controlados proporcionan una perspectiva más rigurosa y han demostrado que, en general, el aumento de peso relacionado con los anticonceptivos hormonales es mínimo. Los resultados indican que la mayoría de los cambios observados pueden atribuirse a la retención temporal de líquidos más que a un incremento real en la grasa corporal. No obstante, estos efectos pueden ser más pronunciados en ciertos subgrupos, como en mujeres con predisposición genética a la obesidad o en aquellas que usan anticonceptivos con progestágenos de alta dosis. Aun así, los estudios controlados generalmente concluyen que los anticonceptivos hormonales no son un factor determinante en el aumento de peso para la mayoría de las mujeres.

**3. Estudios sobre Diferentes Tipos de Anticonceptivos:**
La relación entre anticonceptivos hormonales y obesidad puede diferir según el tipo de anticonceptivo utilizado. Los estudios han mostrado que los anticonceptivos que contienen solo progestágenos, como las píldoras de progestina o los implantes, pueden estar más asociados con cambios en el peso corporal en comparación con los anticonceptivos combinados que incluyen estrógenos y progestágenos. Por ejemplo, se ha observado que los usuarios de anticonceptivos inyectables con progestina tienen un mayor riesgo de aumento de peso en comparación con otros métodos hormonales. Sin embargo, estos aumentos son generalmente modestos y varían dependiendo de la dosis y la duración del uso. En contraste, los anticonceptivos combinados no muestran un impacto significativo en el peso en la mayoría de los estudios, sugiriendo que el estrógeno podría mitigar los efectos de la progestina en el aumento de peso.

### Reflexión y Perspectiva
Un consenso emergente entre los estudios es que la respuesta al uso de anticonceptivos hormonales varía considerablemente entre las mujeres. Factores como la predisposición genética, el tipo específico de anticonceptivo y las características metabólicas individuales influyen significativamente en cómo el cuerpo responde al tratamiento. Esta variabilidad sugiere que, si bien algunas mujeres pueden experimentar un aumento de peso, otras no notarán ningún cambio significativo. La falta de una relación clara y consistente en la literatura sugiere la necesidad de enfoques personalizados en la elección del anticonceptivo, considerando las características individuales y los posibles efectos secundarios.

Este tema abre un debate interesante sobre la importancia de personalizar los tratamientos hormonales y de realizar estudios más detallados que puedan considerar las múltiples variables que afectan la respuesta individual. También se resalta la necesidad de educación y comunicación eficaz entre profesionales de la salud y pacientes para abordar expectativas y preocupaciones sobre los posibles efectos secundarios de los anticonceptivos hormonales .

**¿Por qué el aumento de peso?**

Los anticonceptivos hormonales, que combinan estrógeno y progestina, pueden influir en el apetito, el metabolismo y las funciones digestivas al alterar el equilibrio hormonal del cuerpo. Estos efectos incluyen la modulación del apetito mediante la alteración de hormonas reguladoras como leptina y grelina, cambios en el metabolismo de grasas y carbohidratos que pueden afectar la sensibilidad a la insulina y el almacenamiento de energía, y modificaciones en la motilidad intestinal y la absorción de nutrientes. Además, la retención de líquidos inducida por el estrógeno puede causar un aumento temporal del peso corporal, a menudo confundido con un aumento real. La manifestación de estos efectos varía entre individuos, influenciada por el tipo de anticonceptivo, la dosis y características personales.

**Porque se alteran las hormonas reguladoras (leptina y grelina)**


El uso de anticonceptivos hormonales puede alterar las hormonas reguladoras del apetito, como la leptina y la grelina, debido a su impacto en el equilibrio hormonal general y en los mecanismos de regulación del hambre. La leptina, que es secretada por las células adiposas y actúa para señalar al cerebro sobre el estado de las reservas de grasa en el cuerpo, puede verse afectada por las variaciones en los niveles de estrógeno y progestina. Estas hormonas pueden modificar tanto la producción de leptina como la sensibilidad del cerebro a esta hormona, alterando la percepción de saciedad y el control del apetito. Por otro lado, la grelina, producida principalmente en el estómago y que estimula el apetito, también puede verse influenciada por los anticonceptivos hormonales. El estrógeno y la progestina pueden interferir en la producción y acción de grelina, alterando la señalización que indica la necesidad de alimentación y afectando la regulación del hambre. En conjunto, estos cambios hormonales alteran la forma en que el cuerpo percibe y responde a las señales de hambre y saciedad, lo que puede llevar a un aumento en la ingesta calórica y a variaciones en el peso corporal.
________________________________________________________________


\newpage

- **Anticonceptivos hormonales y su relación con la obesidad en usuarias continuadoras del centro de salud Mala – Cañete, 2021.** <http://repositorio.autonomadeica.edu.pe/handle/autonomadeica/1907>

- **Nappi RE, Pellegrinelli A, Campolo F, Lanzo G, Santamaria V, Suragna A, et al. Effects of combined hormonal contraception on health and wellbeing: women’s knowledge in northern Italy.** Eur J. <https://www.tandfonline.com/doi/epdf/10.1080/09513590.2023.2189971?needAccess=true>

- **Venkat P, Masch R, Ng E, Cremer M, Richman S, Arslan A. Knowledge and beliefs about contraception in urban Latina women.** Contracept Reprod Health Care. 2015;20(1):36–46.

- **Gilliam ML, Warden M, Goldstein C, Tapia B. Concerns about contraceptive side effects among young Latinas: a focus-group approach.** Contraception. 2004;70:288-305.

- **Rosenburg MJ, Waugh MS, Meehan TE. Use and misuse of oral contraceptives: risk indicators for poor pill taking and discontinuation.** Contraception. 1995;51(5):283-8.

- **Sangi-Haghpeykar H, Poindexter AN, Bateman L, Ditmore JR. Experiences of injectable contraceptive users in an urban setting.** Obstet Gynecol. 1996;88(2):227-33.

- **Paul C, Skegg DC, Williams S. Depot medroxyprogesterone acetate. Patterns of use and reasons for discontinuation.** Contraception. 1997;56(4):209-14.

- **Leeners B, Geary N, Tobler PN, Asarian L. Ovarian hormones and obesity.** Hum Reprod Update. 2017;23(3):300-21.

- **Karvonen-Gutierrez C, Kim C. Association of mid-life changes in body size, body composition and obesity status with the menopausal transition.** Healthcare. 2016;4(3).

- **Gallo MF, Lopez LM, Grimes DA, Carayon F, Schulz KF, Helmerhost FM. Combination contraceptives: effects on weight.** Cochrane Database Syst Rev. 2014;(1):CD003987.

- **Lopez LM, Ramesh S, Chen M, Edelman A, Otterness C, Trussel J, et al. Progestin-only contraceptives: effects on weight.** Cochrane Database Syst Rev. 2016;(8):CD008815.





